### ISSUE TITLE
Запускает не ту функцию. Репозиторий сам удаляется

### ISSUE THREAD

**Issue by rrrfer** [MarbleShark/pifagor#2]
После работы с IDE некоторое время (минуту) начинаются проблемы.
Во-первых, жму translate, generate, interpretate - все работает. Жму "Call all" получаю ошибку линковки типа
linkMain: Can't get RIG of function inaccessible_control_1

Наконец, ситуация: случайно нажал "добавить функцию". В открывшемся окне нажал reject (не хотел я ее добавлять), тем не мене, она добавилась в репозиторий. (такая ситуация уже была у меня, но в тот раз я удалил ее вручную). Жму на имя новой функции, выбираю "удалить". Среда перестает реагировать на попытки открытия файлов в панели репозитория (хотя структура репозитория отображается). В проводнике открываю каталог репозитория и ... обнаруживаю что нет такого каталога (видимо он удалился вместе с удалением функции).

**Comment by MarbleShark** [comment]
Убрал Call All, изменил механизм управления выполнением функций.
Репозиторий удаляется автоматически поскольку это явно прописано в конфигурации.
Изменить конфигурацию можно в файле configuration/executor2.conf.
